### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by chourrage** [bitfocus/companion-module-planningcenter-serviceslive#11]
I'm having Issues with initially connecting to pco. After adding the module I entered my personal access token and tried to connect but no success. The connection status in companion says error and the logs just say "404: Not Found". I've tried it with two different accounts and two companion instances but both had the same problem.

Companion Version: 2.2.3
PCO module Version: 1.0.6

**Comment by ericbusby77** [comment]
I am also having the exact same issue as @chourrage above. We are on the same Companion and PCO module versions.

**Comment by isaacclausen** [comment]
Same problem, error on connections page and 404: Not Found...

Companion Version: 2.3.0
PCO module Version: 1.0.6

**Comment by josephdadams** [comment]
What action are you using?

I'm using "Go to Next Item of Next Plan in Selected Service Type" and it works fine.

**Comment by ericbusby77** [comment]
We get an error status and "404: Not Found" error in the logs.

**Comment by josephdadams** [comment]
Yes but what action are you using?

**Comment by josephdadams** [comment]
Or are you saying you never get as far as the action, it just does this in the module config?

**Comment by ericbusby77** [comment]
Yeah, we never get as far as an action. It never connects. Same with the other users above, I believe.

**Comment by ericbusby77** [comment]
![Service Live Module Configuration](https://user-images.githubusercontent.com/72747174/185479516-85a213a3-f2ac-4a11-bd1a-04971977fe6c.jpg)

**Comment by josephdadams** [comment]
Interesting. I was curious if it was re lated to the parent folder and/or restriction of plans.

**Comment by katiewinton** [comment]
I'm having the same issue. I've tried Creating a new specific personal access token, but just keeps giving me the 404 error in the log

**Comment by josephdadams** [comment]
I just pushed a fix for this in the latest betas.
