### ISSUE TITLE
Send chat message action

### ISSUE THREAD

**Issue by Xcodo** [bitfocus/companion-module-planningcenter-serviceslive#12]
I don't think this is available in the API, but I still wanted to flag it in case I've missed something.

It would be very useful to us to be able to send a preset message to PCO Live with a Companion button. When people send a "suggestion" to the tech desk we like to respond quickly with an acknowledgement, which is usually a single word we could standardise. A Companion button would mean we don't need to switch focus on a PC.

Close if it's not possible.

**Comment by josephdadams** [comment]
Like in the chat?

**Comment by Xcodo** [comment]
Yes 🙂

**Comment by josephdadams** [comment]
Don't think this is possible in the PCO Live API. What OS are you running? It could be possible to write an AppleScript on MacOS that targets a browser tab and executes Javascript. All depends on the OS and the browser.

You might also be able to use Vicreo Listener and the Vicreo Hotkey module to cmd+tab or alt+tab to the browser window, type the message and send it, and cmd+tab or alt+tab back, all from a Companion button.
