### ISSUE TITLE
Variables not working in Go to Next Item of a Specific Plan

### ISSUE THREAD

**Issue by Xcodo** [bitfocus/companion-module-planningcenter-serviceslive#13]
I'm trying to load variables in the "Go to Next Item of a Specific Plan" and "Go to Previous Item of a Specific Plan" actions.

I have this variable setup
![image](https://user-images.githubusercontent.com/6715247/206919882-c6700095-d516-4689-a07f-beace5c3b77e.png)

This action does nothing (no error, but no change in the Live position either)
![image](https://user-images.githubusercontent.com/6715247/206919925-757dc59b-2cad-4453-bc23-436ced8c5499.png)

While this one works fine
![image](https://user-images.githubusercontent.com/6715247/206919955-7a5da859-4511-44d5-a132-6a39d1b6cd0d.png)

Does something need to be added to enable variable parsing in an action config?

(I am using 2.3.1, but I don't see anything in the release notes for 2.4.x that would change this. Upgrading is an after Christmas service problem!)

**Comment by josephdadams** [comment]
Yes, this has to be implemented on a per module basis and it’s not in this one

**Comment by Xcodo** [comment]
Ah okay. I see how it can be added (like [here](https://github.com/bitfocus/companion-module-bitfocus-companion/commit/8b208d91afab6ef95d87ba66709a11cc83383303)), so I'll do a PR this week 👍.

**Comment by josephdadams** [comment]
I'll accept the PR, but know that it likely won't make its way in to the betas of Companion until the module is refactored to be compatible with the 3.0 API: https://github.com/bitfocus/companion-module-base/wiki/Upgrading-a-module-built-for-Companion-2.x

**Comment by Xcodo** [comment]
Thanks. I'd seen that coming. TypeScript isn't a language I've done tons of, but I'd like to see if I can find some time to give something back in the 3.0 conversion.

**Comment by josephdadams** [comment]
TS isn’t necessary. ES6 will be fine

**Comment by josephdadams** [comment]
This is implemented in the new v3 version which will be available shortly in the betas

**Comment by Xcodo** [comment]
Thanks for your effort here
