### ISSUE TITLE
'Go to Next Item' sending in PST

### ISSUE THREAD

**Issue by mixmastrbrock** [bitfocus/companion-module-planningcenter-serviceslive#15]
Not sure if this is on the Planning Center API side or from the module, but when sending the 'Go to Next Item' command, it strictly sends in PST. So, this shows a service that occurs in EST as three hours behind, making this module unusable currently. When controlling in browser, it behaves as expected.

System time on the computer running Companion is in the correct time zone.

**Comment by josephdadams** [comment]
I don't see how this could be happening on the module side because it just sends a "go to next item" command, it does not reference time at all. So it is either on the PCO API side or something on the end user side.
