### ISSUE TITLE
next and previous no longer work

### ISSUE THREAD

**Issue by justingiffard** [bitfocus/companion-module-planningcenter-serviceslive#16]
Upgraded to 3.0.0.rc1 and next and previous actions no longer responds
I tried resetting my keys and deleting and recreating the buttons

Running on a MacMini with M2 Pro

**Comment by josephdadams** [comment]
Do you get any errors?

**Comment by ldhall1856** [comment]
I'm seeing the same issue.  I use this week end and week out.... I also changed the token and Secret code and it shows connected but doesn't go next, prev, of even take control.

**Comment by josephdadams** [comment]
Which actions are you using? I use “go to next item of next plan in service type” weekly. Never have to touch any config and it works flawlessly.

**Comment by ldhall1856** [comment]
Go to next. It stopped working when I upgraded to 3.0

**Comment by josephdadams** [comment]
This is fixed now, it was a bad function name `getServiceTypeIdFromPlanId` instead of `getServiceIdFromPlanId`.

v2.0.1 of the module has the fix. https://github.com/bitfocus/companion-bundled-modules/actions/runs/5807382256
