### ISSUE TITLE
Planning Centre Online - Services Live

### ISSUE THREAD

**Issue by mcondie65** [bitfocus/companion-module-planningcenter-serviceslive#2]
**PCO Services Live Plan Selection**
Currently you need to go in and select the plan which you want the PCO Live module to control, which means each week you need to go into the button settings to update. It would be good if the module automatically selects the next available service plan when the specific service plan is specified in the instance settings. 

**PCO Services Live "Next Item" variable**
A next item variable so you can display what is following the current item would be ideal.

**Usecases**
**PCO Services Live Plan Selection**
This would automatically control the most recent service in you plan enabling easier use for volunteers who work with the stream deck each week.

**PCO Services Live "Next Item" variable**
This could be a button that displays the next item so you know to advance to the next item.

**Comment by josephdadams** [comment]
I transferred this to the PCO module repo.

**Comment by josephdadams** [comment]
I am the author of this module. The first thing you asked for was added over 9 months ago, so my guess is you are running an old version of Companion. Please consider upgrading.

**Comment by mcondie65** [comment]
I'm using Companion v1.4.0
Currently I have the Service Type ID and the Parent Folder ID in the settings. However when I press the button without selecting a plan I receive this error:
<img width="615" alt="Screen Shot 2020-03-10 at 3 12 31 pm" src="https://user-images.githubusercontent.com/60452153/76279234-00933600-62e2-11ea-89e9-f9aca2083aca.png">
<img width="403" alt="Screen Shot 2020-03-10 at 3 14 25 pm" src="https://user-images.githubusercontent.com/60452153/76279238-0426bd00-62e2-11ea-9a07-0fb66f741039.png">
<img width="466" alt="Screen Shot 2020-03-10 at 3 15 54 pm" src="https://user-images.githubusercontent.com/60452153/76279247-0f79e880-62e2-11ea-91a1-750809a87165.png">

Am I missing something to get this to work?

Thanks for your help both here and on the facebook group!

**Comment by josephdadams** [comment]
Is there a reason you’re not selecting a plan?

**Comment by mcondie65** [comment]
It works when I select a plan, but it doesn't update to the next newest plan each week, it returns back to this blank drop down box. We have to select a plan every week.

**Comment by josephdadams** [comment]
It looks like the version of Companion you are using does not have that action. It is called “Go to Next Item of Next Plan in Selected Service Type”.

**Comment by mcondie65** [comment]
Ah yes I see that function now. This will advance to the next item within the current plan selected, and advance the plan when one isn't selected?

Thanks so much.

**Comment by josephdadams** [comment]
When using that action, you select the service type and it will advance the next plan in that service type. Once the date has passed for that plan, it will look for the next plan in the service type. It’s all based on what the PCO API returns using the future filter. But the end result is what you want.

**Comment by josephdadams** [comment]
@mcondie65 I've added a plan_nextitem variable. When it gets put into the Companion core, you can download the latest build and try it out.

**Comment by sascha9424** [comment]
I've just found out about this module, but there ist a problem with the “Go to Next Item of Next Plan in Selected Service Type” button. The plans are sorted by months, though not but years. That means, if use thise button right now and I have an existing plan in october but also one in april next year, this button will use the april plan of next year instead of the timewise closer october plan. Here is a screenshot, when you use the "normal" Go To Next Item Button and you ave to manually select a plan, you can see that it is sorting the plan this way [https://ibb.co/7JS8yZr](url)
I hope this can be fixed as we often have plans of two years at the same time in PCO

**Comment by sascha9424** [comment]
> @mcondie65 I've added a plan_nextitem variable. When it gets put into the Companion core, you can download the latest build and try it out.

Do you have any idea when this will be available? I think I've read you read saying somewhere, that you made a button displaying the current item text. Is that also not available yet?!

**Comment by josephdadams** [comment]
@sascha9424 please open a new issue for your sorting problem. This is the way the data is returned from PCO, but it's possible I can fix it.

Regarding the new next item variable, that was added 7 months ago, so make sure you are running the latest version of Companion.

**Comment by sascha9424** [comment]
I opened a new issue regarding the sorting problem.

Regarding the new next item variable, I just downloaded the companion software a week ago, that's why I'm so suprised I can't find it. Any ideas on that?

**Comment by josephdadams** [comment]
Which version did you download?

**Comment by sascha9424** [comment]
2.1.0 (47823d0-2493)

**Comment by sascha9424** [comment]
Nevermind my mistake, everything is there!
