### ISSUE TITLE
Connection Failure 401: Unauthorized

### ISSUE THREAD

**Issue by justingiffard** [bitfocus/companion-module-planningcenter-serviceslive#20]
Not sure if its Planning Center that is having issues with their API or not.
https://status.planningcenter.com seems to think everythings running smoothly although I am getting "Error: Network Error" on every page on  https://developer.planning.center/docs/#/apps/api which... suggests things might not be as healthy as they claim. Also getting  

```
Your connection is not private
Attackers might be trying to steal your information from api.planningcenteronline.com (for example, passwords, messages or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_COMMON_NAME_INVALID
```
On http://api.planningcenteronline.com/

Im assuming its a Planning Center issue not the Companion module issue but leaving this here incase

**Comment by justingiffard** [comment]
Update: all above mentioned urls seem to be working fine now [suspicious Fry meme] yet https://status.planningcenter.com still has no mention of an outage. I shall check on Sunday morning and hopefully it works again. Will close this ticket if its working

**Comment by josephdadams** [comment]
It was working fine for me earlier today

**Comment by justingiffard** [comment]
Nope she's still dead. I tried creating a new instance and changing my application ID and secret with no luck :(

![Screenshot 2023-08-13 at 07 21 39](https://github.com/bitfocus/companion-module-planningcenter-serviceslive/assets/3730862/16a5bd72-d286-4d59-a1f3-69e507104170)

![Screenshot 2023-08-13 at 07 22 05](https://github.com/bitfocus/companion-module-planningcenter-serviceslive/assets/3730862/c55bbd2a-aa07-4817-a5f6-eddd51bcd98f)

I'm running Companion `v3.1.0+6088-beta-9c309603`

**Comment by justingiffard** [comment]
Removing the instance and adding again seemed to have worked? Yet when I just added a new instance on Thursday nothing happened
¯\\_(ツ)_/¯

Closing ticket for now
