### ISSUE TITLE
Plan Next Item not displaying songs

### ISSUE THREAD

**Issue by dmlodzik** [bitfocus/companion-module-planningcenter-serviceslive#21]
When using the variable $(PCO:plan_nextitem) it wont list any of our songs.  Everything else is displayed and works properly, when using to advance through PCO live it still triggers each song, but the next item will not display any items added as a song.  Currently running companion version 3.1.1

**Comment by tyler351** [comment]
I'm having the same issue on version 3.1.2. It seems that is the case with any PCO services API version, not just the latest.

**Comment by josephdadams** [comment]
I will fix it at some point

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-planningcenter-serviceslive/blob/a7817440ae119ae5a666654e4f15a2af77ee5f38/src/api.js#L531C9-L531C9

This general area

**Comment by josephdadams** [comment]
Try the latest v2.0.2 of the module

**Comment by tyler351** [comment]
> Try the latest v2.0.2 of the module

Looks good on my end! Thanks for knocking that out so quick!

**Comment by josephdadams** [comment]
You’re welcome!
