### ISSUE TITLE
Add Services Live Countdown Timers

### ISSUE THREAD

**Issue by B00TK1D** [bitfocus/companion-module-planningcenter-serviceslive#3]
Feature request - it would be really nice if you could add variables for the countdown timer from PCO Live, showing how much time is left until the next item, or how much over time the current item is.

**Comment by josephdadams** [comment]
That timer is calculated locally. Which means if you advanced PCO from another device, that timer could get off easily. The PCO module does not currently do any “polling” to get the state of a plan. It only refreshes its dataset when an action is performed, like advancing a plan. This is to avoid rate limits of the API. You would have to commit to using one specific instance of Companion only to advance the plan.

**Comment by josephdadams** [comment]
Closing as this is something we can't easily implement due to the rate limits of the PCO API.
