### ISSUE TITLE
Services Live Integration Not Working in Companion 2.1.0

### ISSUE THREAD

**Issue by dronenb** [bitfocus/companion-module-planningcenter-serviceslive#6]
I am unable to take control and advance planning center services using Companion 2.1.0. It worked fine with 1.4.0. Haven't had time to dig through the code to see where it's failing. It still queries the plan information correctly, but advancing and taking control doesn't seem to do anything.

**Comment by josephdadams** [comment]
Working for me on 2.1.0.

**Comment by dronenb** [comment]
Interesting. I've tried on several machines with the same result. I'll see if I can dig into the code sometime next week and figure out what's happening (btw, love your blog @josephdadams).

**Comment by josephdadams** [comment]
Thank you! Let me know what you find out. And I'm glad you enjoy the blog! 😃

**Comment by josephdadams** [comment]
@dronenb any progress?

**Comment by josephdadams** [comment]
We are using it in 2.1.1 without issue! So let me know if you’re still having issues. In the mean time, I will close this.

**Comment by dronenb** [comment]
Sorry it's taken me so long to get back with this. I'm still experiencing this issue on macOS on the latest build of Companion. I made a quick YouTube video demoing the issue. Like I said, I was not experiencing this issue in build 1.4.0, but I can't prove that since I no longer have a copy of 1.4.0 and I can't seem to find a download link on the Bitfocus website. See here: https://youtu.be/L3Zkv0uOR7E

**Comment by josephdadams** [comment]
@dronenb does it work if you select something in the drop down list of plans besides the first one? Even if you selected the second or third item, and then let that save, and then selected the first item in the drop down list again?

**Comment by dronenb** [comment]
@josephdadams Good idea, I thought I'd tried that but I guess I didn't. That does seem to work. So I guess the issue is specifically when a new button is created and the first plan on the list is automatically "selected".

**Comment by josephdadams** [comment]
It's because of this: https://github.com/bitfocus/companion/issues/1029

It doesn't save when the list is dynamically populated, and we aren't specifying a default (since the list is dynamic).

**Comment by josephdadams** [comment]
I pushed an update to this module just now that will take care of this issue going forward where the default is always "(choose a plan)" and you have to select something different.
