### ISSUE TITLE
Variables Not Returning Values in V2.1.1

### ISSUE THREAD

**Issue by michaelferris** [bitfocus/companion-module-planningcenter-serviceslive#9]
I am unable to use the variables in the latest version of companion. I know the instance is properly setup as I'm able to use all the button actions as intended, it's just the variables that aren't working as expected.

**Comment by josephdadams** [comment]
It's working fine here. Are you getting an error message of any kind?

**Comment by michaelferris** [comment]
There's no error messages, everything else works fine. For example I have $(services-live:plan_index) as a button title and it just leaves the title blank even though something should definitely be there.

**Comment by josephdadams** [comment]
Did you rename the instance? Do the variable show up if you edit the instance settings and look at the variable values there?

**Comment by michaelferris** [comment]
The instance name hasn't been changed and the variables don't show up in instance settings. A few days ago it worked for like 20 minutes and then just stopped working again. Checked logs and nothing noteworthy there.
